#####SMALI COMMANDS RULES#####
cmdAny =  cmdConst;
cmdAny =/ cmdConst16;
cmdAny =/ cmdConst4;
cmdAny =/ cmdConstHigh16;
cmdAny =/ cmdConstString;
cmdAny =/ cmdConstWide;
cmdAny =/ cmdConstWide16;
cmdAny =/ cmdConstWide32;
cmdAny =/ cmdConstWideHigh16;
cmdAny =/ cmdGoto;
cmdAny =/ cmdIfEq;
cmdAny =/ cmdIfEqz;
cmdAny =/ cmdIfNe;
cmdAny =/ cmdIfNez;
cmdAny =/ cmdIget;
cmdAny =/ cmdIgetObject;
cmdAny =/ cmdIgetWide;
cmdAny =/ cmdInvokeDirect;
cmdAny =/ cmdInvokeInterface;
cmdAny =/ cmdInvokeStatic;
cmdAny =/ cmdInvokeVirtual;
cmdAny =/ cmdIput;
cmdAny =/ cmdIputObject;
cmdAny =/ cmdIputWide;
cmdAny =/ cmdMove;
cmdAny =/ cmdMoveResultObject;
cmdAny =/ cmdNewInstance;
cmdAny =/ cmdNop;
cmdAny =/ cmdReturn;
cmdAny =/ cmdReturnObject;
cmdAny =/ cmdReturnVoid;
cmdAny =/ cmdReturnWide;
cmdAny =/ cmdSgetObject;
cmdAny =/ cmdSputObject;

cmdConst            = optPadding "const" padding codeRegisterVDst listSeparator intValue optPadding [padding commentSequence] CRLF;
cmdConst16          = optPadding "const/16" padding codeRegisterVDst listSeparator intValue optPadding [padding commentSequence] CRLF;
cmdConst4           = optPadding "const/4" padding codeRegisterVDst listSeparator intValue optPadding [padding commentSequence] CRLF;
cmdConstHigh16      = optPadding "const/high16" padding codeRegisterVDst listSeparator intValue optPadding [padding commentSequence] CRLF;
cmdConstString      = optPadding "const-string" padding codeRegisterVDst listSeparator strValue optPadding [padding commentSequence] CRLF;
cmdConstWide        = optPadding "const-wide" padding codeRegisterV64Dst listSeparator intValue optPadding [padding commentSequence] CRLF;
cmdConstWide16      = optPadding "const-wide/16" padding codeRegisterV64Dst listSeparator intValue optPadding [padding commentSequence] CRLF;
cmdConstWide32      = optPadding "const-wide/32" padding codeRegisterV64Dst listSeparator intValue optPadding [padding commentSequence] CRLF;
cmdConstWideHigh16  = optPadding "const-wide/high16" padding codeRegisterV64Dst listSeparator intValue optPadding [padding commentSequence] CRLF;
cmdGoto             = optPadding "goto" padding codeLabel optPadding [padding commentSequence] CRLF;
cmdIfEq             = optPadding "if-eq" padding codeRegister listSeparator codeRegister listSeparator codeLabel optPadding [padding commentSequence] CRLF;
cmdIfEqz            = optPadding "if-eqz" padding codeRegister listSeparator codeLabel optPadding [padding commentSequence] CRLF;
cmdIfNe             = optPadding "if-ne" padding codeRegister listSeparator codeRegister listSeparator codeLabel optPadding [padding commentSequence] CRLF;
cmdIfNez            = optPadding "if-nez" padding codeRegister listSeparator codeLabel optPadding [padding commentSequence] CRLF;
cmdIget             = optPadding "iget" padding codeRegisterVDst listSeparator codeRegister listSeparator smaliFieldRef optPadding [padding commentSequence] CRLF;
cmdIgetObject       = optPadding "iget-object" padding codeRegisterVDst listSeparator codeRegister listSeparator smaliFieldRef optPadding [padding commentSequence] CRLF;
cmdIgetWide         = optPadding "iget-wide" padding codeRegisterV64Dst listSeparator codeRegister listSeparator smaliFieldRef optPadding [padding commentSequence] CRLF;
cmdInvokeDirect     = optPadding "invoke-direct" padding codeRegisterGroup listSeparator smaliMethodRef optPadding [padding commentSequence] CRLF;
cmdInvokeInterface  = optPadding "invoke-interface" padding codeRegisterGroup listSeparator smaliMethodRef optPadding [padding commentSequence] CRLF;
cmdInvokeStatic     = optPadding "invoke-static" padding codeRegisterGroup listSeparator smaliMethodRef optPadding [padding commentSequence] CRLF;
cmdInvokeVirtual    = optPadding "invoke-virtual" padding codeRegisterGroup listSeparator smaliMethodRef optPadding [padding commentSequence] CRLF;
cmdIput             = optPadding "iput" padding codeRegister listSeparator codeRegister listSeparator smaliFieldRef optPadding [padding commentSequence] CRLF;
cmdIputObject       = optPadding "iput-object" padding codeRegister listSeparator codeRegister listSeparator smaliFieldRef optPadding [padding commentSequence] CRLF;
cmdIputWide         = optPadding "iput-wide" padding codeRegister64 listSeparator codeRegister listSeparator smaliFieldRef optPadding [padding commentSequence] CRLF;
cmdMove             = optPadding "move" padding codeRegisterVDst listSeparator codeRegister optPadding [padding commentSequence] CRLF;
cmdMoveResultObject = optPadding "move-result-object" padding codeRegisterVDst optPadding [padding commentSequence] CRLF;
cmdNewInstance      = optPadding "new-instance" padding codeRegisterVDst listSeparator smaliClassRef optPadding [padding commentSequence] CRLF;
cmdNop              = optPadding "nop" optPadding [padding commentSequence] CRLF;
cmdReturn           = optPadding "return" padding codeRegisterRet optPadding [padding commentSequence] CRLF;
cmdReturnObject     = optPadding "return-object" padding codeRegisterRet optPadding [padding commentSequence] CRLF;
cmdReturnVoid       = optPadding "return-void" optPadding [padding commentSequence] CRLF;
cmdReturnWide       = optPadding "return-wide" padding codeRegisterRet64 optPadding [padding commentSequence] CRLF;
cmdSgetObject       = optPadding "sget-object" padding codeRegisterVDst listSeparator smaliFieldRef optPadding [padding commentSequence] CRLF;
cmdSputObject       = optPadding "sput-object" padding codeRegister listSeparator smaliFieldRef optPadding [padding commentSequence] CRLF;
